defaults:
  - model: standard_vae
  - backbone: conv
  - dataset: fashion_mnist
  - trainer: default
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - _self_

# Hydra configuration
hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

# General settings
seed: 42
experiment_name: "${dataset.name}_${model.name}_${backbone.name}_${trainer.name}"
output_dir: ${hydra:run.dir}
enable_visualization: true
save_model: true